#!/bin/bash

# Generate hyprlock.conf from current theme
# This script reads the theme variables and generates a hyprlock configuration

THEME_FILE="$HOME/.config/hypr/themes/current.conf"
LOCK_CONF="$HOME/.config/hypr/hyprlock.conf"
WALLPAPER_PATH="/home/dinesh/Downloads/Wallpapers/zenitsu.png"

# Function to extract color from theme file
get_color() {
    local var_name=$1
    grep "^$var_name = " "$THEME_FILE" | sed 's/.*= //'
}

# Read theme colors
BG_PRIMARY=$(get_color '\$bg_primary')
BG_SECONDARY=$(get_color '\$bg_secondary')
TEXT_PRIMARY=$(get_color '\$text_primary')
TEXT_SECONDARY=$(get_color '\$text_secondary')
ACCENT_PRIMARY=$(get_color '\$accent_primary')
BORDER_ACTIVE=$(get_color '\$border_active')

# Generate hyprlock.conf
cat > "$LOCK_CONF" << EOF
# Auto-generated hyprlock configuration
# This file is generated by theme-switcher.sh - manual changes will be overwritten

background {
    monitor =
    path = $WALLPAPER_PATH
    blur_passes = 3
    blur_size = 7
}

# The Clock (Above)
label {
    monitor = 
    text = cmd[update:1000] echo "\$(date +"%H:%M")"
    font_size = 180
    font_family = Ubuntu Nerd Font Bold
    position = 0, 150
    valign = center
    halign = center
    color = $TEXT_PRIMARY
}

# Date label
label {
    monitor = 
    text = cmd[update:1000] echo "\$(date +"%A, %B %d")"
    font_size = 24
    font_family = Ubuntu Nerd Font
    position = 0, 50
    valign = center
    halign = center
    color = $TEXT_SECONDARY
}

# The Password Field
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true
    
    outer_color = $BORDER_ACTIVE
    inner_color = $BG_SECONDARY
    font_color = $TEXT_PRIMARY
    
    fade_on_empty = true
    fade_timeout = 1000
    
    placeholder_text = <span foreground="##$(echo $TEXT_SECONDARY | sed 's/rgba(\(.\{6\}\).*/\1/')">Password...</span>
    hide_input = false
    
    position = 0, -100
    halign = center
    valign = center
    
    check_color = $ACCENT_PRIMARY
    fail_color = $(get_color '\$accent_error')
}

# User label
label {
    monitor = 
    text = \$USER
    font_size = 18
    font_family = Ubuntu Nerd Font
    position = 0, -180
    valign = center
    halign = center
    color = $TEXT_SECONDARY
}
EOF

echo "Generated hyprlock.conf from current theme"
